skip_output = ["meta", "skips"]

[pre-commit]
follow = true
parallel = true

[pre-commit.commands.lint]
glob = "*.go"
run = "golangci-lint run --out-format=tab --fix"
tags = "go,lint"

[pre-commit.commands.test]
glob = "*.go"
run = "go test ./... -race"
tags = "go,test"

[prepare-commit-msg.commands.gitmoji]
run = "gitmoji --hook {0} {1}"
interactive =  true
