name: Go
on:
  pull_request:
    paths: [cmd/**, pkg/**, go.mod, go.sum, .github/workflows/go.yaml]
  push:
    branches: [main]
    paths: [cmd/**, pkg/**, go.mod, go.sum, .github/workflows/go.yaml]

jobs:
  lint:
    name: Lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # renovate: tag=v3.2.0
      with:
        go-version: 1.18
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # renovate: tag=v3.2.0
      with:
        version: latest

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.18]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # renovate: tag=v3.2.0
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # renovate: tag=v3.1.0
      env:
        OS: ${{ matrix.os }}
        GO_VERSION: ${{ matrix.go }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        env_vars: GO_VERSION
        fail_ci_if_error: true
        flags: unittests
        verbose: true
