name: Lint everything (Trunk)

on:
  merge_group: {}
  pull_request: {}

permissions: read-all

jobs:
  trunk:
    name: Trunk Check
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.21
      - uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: latest
          args: --help # Just force the action to download the latest version of golangci-lint

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
