name: Test code (Go)
on:
  pull_request:
    paths: 
      - "**/*.go"
      - go.mod
      - go.sum
      - .github/workflows/pull_request,push.go.test.yaml
  push:
    branches: [main]

jobs:
  test:
    name: Go test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.21]
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # renovate: tag=v5.0.0
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3.0.2
    - run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # renovate: tag=v3.1.0
      env:
        OS: ${{ matrix.os }}
        GO_VERSION: ${{ matrix.go }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        env_vars: GO_VERSION
        fail_ci_if_error: true
        flags: unittests
        verbose: true
