name: Synchronize labels
on:
  push:
    branches: [main]
    paths: [.github/workflows/github.labeler.yaml, .github/labels.yaml]

jobs:
  sync:
    name: Synchronize labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # renovate: tag=v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        manifest: .github/labels.yaml
        prune: true
